Repository eu-digital-green-certificates/dgc-lib, pull requests merged in 2021-05, with the labels that each got.

#18 docs: Update contributing
  CONTRIBUTING.md
Labels: documentation

#21 Fix: Wrong Endpoints for Uploading/Deleting Certificates
  src/main/java/eu/europa/ec/dgc/gateway/connector/client/DgcGatewayConnectorRestClient.java
Labels: bug

#22 Hotfix: Disable Uploader Certificate Check
  README.md
  src/main/java/eu/europa/ec/dgc/gateway/connector/DgcGatewayDownloadConnector.java
  src/main/java/eu/europa/ec/dgc/gateway/connector/config/DgcGatewayConnectorConfigProperties.java
Labels: bug

#23 Fix: Signature Calculation of Signed CMS
  src/main/java/eu/europa/ec/dgc/signing/SignedCertificateMessageParser.java
  src/test/java/eu/europa/ec/dgc/signing/SignedCertificateMessageParserTest.java
Labels: bug

#30 Update Dependencies
  pom.xml
Labels: enhancement

#31 Add BouncyCastle Provider to SecurityContext
  src/main/java/eu/europa/ec/dgc/gateway/connector/DgcGatewayDownloadConnector.java
  src/main/java/eu/europa/ec/dgc/signing/SignedCertificateMessageBuilder.java
  src/main/java/eu/europa/ec/dgc/signing/SignedCertificateMessageParser.java
Labels: bug
